### ISSUE TITLE
Store Ducc values inside userdata

### ISSUE THREAD

**Issue by wyozi** [SkylerLipthay/ducc#10]
Hey, great library! I have a usecase where I'm trying to store hooks (`ducc::Function`s) inside userdata, so they can be called from Rust code later when needed. However, the `'static` lifetime requirement for userdata values is making this quite difficult.

How viable do you think it would be to change the `set_user_data` data lifetime to for instance `'ducc`? As far as I understand, this would then make it possible to store Ducc values inside userdata.

**Comment by SkylerLipthay** [comment]
Hi, thank you! This is related to a problem I'm mulling over at SkylerLipthay/mini-v8#4. Unfortunately it's impossible to downcast data of any lifetime other than `'static` (`'static` is required by `std::any::Any`). My suggestion is the same as in that other issue: keep JS functions in JS-land. You could either store your callbacks in the `Ducc::global()` object or in whatever object/namespace from which you'll be calling your callbacks. I'd be happy to advise further if you wouldn't mind sharing your use case more!

**Comment by wyozi** [comment]
Ah, good to know about that library as well.

Moving to JS-land works fine for that usecase, but I have another requirement where that may unfortunately by impossible. I have bunch of "entity" .js files stored in `entities/` folder, each of which is a self-contained Javascript class. Then in my main javascript file `main.js` I instantiate and interact with entity classes.

The way it works is that each entity file can be re-registered individually, so at some point code like this should be possible:
```js
const ent = instantiateEntity();
ent.func(); // does thing A
sleep(10 seconds); // during this time the entity can be re-registered with a new implementation 'B' for func
ent.func(); // does thing B
```
It's a bit hard to explain, but I hope you get the gist. Basically, I want to store the implementation functions in Rust-world, so that some functions can be hot-replaced on demand.

Maybe this would be achievable with unsafe casts? I expect the same Ducc instance to be there for essentially duration of the whole binary lifetime, so hacking around a bit should be ok in this case.

**Comment by wyozi** [comment]
Okay, a few minutes of thinking later some kind of global registry object is likely the way to go for this as well. It does mean that all function calls need to be proxied with a small performance hit, but that was gonna be the way to go with storing things in Rust as well. Seems like Duktape supports `Proxy`-objects at least in JS world, so this should be very doable. Thanks for help!

**Comment by SkylerLipthay** [comment]
Yeah either using some `Proxy` magic, or hot-swapping the function directly on `ent` or its prototype perhaps (using `ducc::Object::set`, pulling from the global registry)?

A downside is that you're forced to reveal the registry in JS-land somewhere (in the global object or elsewhere). This might not be a problem for you. But if it is, Duktape supports adding hidden properties onto objects so that only C/Rust code can access them. I just never got around to exposing that API.

As far as performance I've had similar considerations lately, but what I've realized is that for the majority of cases the biggest bottleneck is going to be the JS interpretation/execution itself. Especially with Duktape since it doesn't have a JIT runtime like e.g. V8.

Let me know if I can be of further help! Feel free to reopen this issue.

e: Oh and about `unsafe`... I was going to recommend `transmute`ing the lifetimes away but I honestly have no idea what the consequences of that are 🙃
