### ISSUE TITLE
Unhandled fatal error causes stack overflow

### ISSUE THREAD

**Issue by tcosprojects** [SkylerLipthay/ducc#9]
When testing JS errors I found that there is not a clear way to handle this error without the program crashing.

Rust code:
```
use ducc::{Ducc, ExecSettings};

fn main() {
    let ducc = Ducc::new();
    ducc.exec("throw 'test'", None, ExecSettings::default()).unwrap()
}
```

Running this code on rust 1.42.0 stable-i686-pc-windows-msvc results in:
```
     Running `target\debug\ducctest.exe`
fatal error from duktape: uncaught: 'cannot write property [Symbol hidden \x27?error\x27] of \x27test\x27'
error: process didn't exit successfully: `target\debug\ducctest.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

Is there another way to wrap exec so that these errors can be handled? Thank you.

**Comment by SkylerLipthay** [comment]
Oh nice catch! The error handling logic was not accounting for cases where the thrown error was a non-object. This has been fixed in 9c1bedafc99e3246914ce9d2a8d4d09e6d644b24 and published on crates.io @ version `0.1.4`.

Hopefully this fix is good enough for your current purposes. Unfortunately the `Error` that you'll get from `ducc.exec("throw 'test'", ...)` is just a generic one, with no visibility into `'test'`. While writing `mini-v8` (this crate except with V8 instead of Duktape) I discovered it was ergonomic to have an [`Error::Value` variant](https://github.com/SkylerLipthay/mini-v8/blob/master/src/error.rs#L38) so the `exec` caller could see—in your case—`Value::String("test")`. This sort of error handling should probably be ported back into `ducc`.
